/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cucumber.unitTests;

import org.junit.Test;

import com.cucumber.core.Core;

import static org.junit.Assert.*;

public class LibraryTest {   

	@Test
	public void Hello(){
		System.out.println("Hello");
	}
	
}
